209 Push to stream
fluencelabs/aqua pull request #214
Opened 2021-07-23 13:49 UTC by DieMyst

fixes #209

2021-07-23 14:09 UTC, alari requested changes

2021-07-23 14:09 UTC, alari commented on parser/src/main/scala/aqua/parser/expr/PushToStreamExpr.scala
> +  stream: VarLambda[F],
You just need to read `Name[F]`, as you can't write to a stream with lambda. E.g. `stream! <<- "val"` is incorrect.

2021-07-23 14:09 UTC, alari commented on semantics/src/main/scala/aqua/semantics/expr/PushToStreamSem.scala
> +          resolvedStreamType <- N.read(expr.stream.name).map(_.get)
This is unsafe.

2021-07-23 14:09 UTC, alari commented on semantics/src/main/scala/aqua/semantics/expr/PushToStreamSem.scala
> +          _ <- T.expectStreamMember(expr.value, resolvedStreamType, valueType)
You can build both checks from `ValuesAlgebra.ensureTypeMatches`

2021-07-23 14:09 UTC, alari commented on semantics/src/main/scala/aqua/semantics/expr/PushToStreamSem.scala
> +              CallServiceTag(
Use `FuncOps.identity` builder instead.

2021-07-26 11:15 UTC, alari approved these changes

2021-07-26 11:31 UTC, DieMyst commented
fixes #209

2021-07-26 11:31 UTC, merged